/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ControleArquivo;
import controle.ControleComunicacao;
import controle.ControleProgramacao;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.TransferHandler;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelo.Comando;
import modelo.Programacao;
import org.json.JSONException;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Vitor
 */
public class FrmEditorComandos extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    int qntdLinhas = 6;
    int qntdColunas = 9;
    int qntdComandos = 5;

    String nomeProjeto = null;
    File diretorioProjeto = new File(System.getProperty("user.dir"));

    JLabel[][] lineMatriz = new JLabel[qntdLinhas][qntdColunas];
    JLabel[] labelLine = new JLabel[qntdLinhas * qntdColunas];
    JLabel[] labelContatos = new JLabel[qntdComandos];
    LinkedList<Comando> listaComandos = new LinkedList<Comando>();
    JSONObject jsonComandos = new JSONObject();
    Programacao prog = new Programacao();

    public void novoProjeto(String nome, File diretorio) {
        nomeProjeto = nome;
        diretorioProjeto = diretorio;
    }

    public FrmEditorComandos() {

        initComponents();
        setLocationRelativeTo(null);
        populaVariaveis();
        movimentacoesBlocosEntrada();
        this.setIconImage(new ImageIcon(getClass().getResource("/icones/LogoVGS_icon.png")).getImage());
        this.setExtendedState(MAXIMIZED_BOTH);

    }

    public void abrirProjeto(String nome, File diretorio, JSONObject progSalva) throws JSONException {
        nomeProjeto = nome;
        diretorioProjeto = diretorio;

        JSONObject portas = (JSONObject) progSalva.get("portas");
        JSONObject comandos = (JSONObject) progSalva.get("comandos");

        System.out.println(progSalva);
        System.out.println(portas);
        System.out.println(comandos);

        for (int i = 0; i < labelLine.length; i++) {
            ImageIcon ico;
            String path = (String) comandos.get("comando" + i);

            ico = new ImageIcon(System.getProperty("user.dir") + "/src/icones/" + path, "label");

            labelLine[i].setIcon(ico);
            labelLine[i].setText((String) portas.get("porta" + i));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jToolBar1 = new javax.swing.JToolBar();
        btnArquivo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        salvarComo = new javax.swing.JButton();
        btnConfiguraPorta = new javax.swing.JButton();
        btnVerificaConexao = new javax.swing.JButton();
        btnConfiguracao = new javax.swing.JButton();
        btnCarregar = new javax.swing.JButton();
        lblContatoNA = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblContatoP = new javax.swing.JLabel();
        lblContatoNF = new javax.swing.JLabel();
        lblContatoN = new javax.swing.JLabel();
        lblSaidaNF = new javax.swing.JLabel();
        lblSaidaP = new javax.swing.JLabel();
        lblSaidaN = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ptxtSaida = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        btnLimparSaida = new javax.swing.JButton();
        cbxAtivarSaida = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        lbLocal3_5 = new javax.swing.JLabel();
        lbLocal3_6 = new javax.swing.JLabel();
        lbLocal3_7 = new javax.swing.JLabel();
        lbLocal3_8 = new javax.swing.JLabel();
        lbLocal3_9 = new javax.swing.JLabel();
        lbLocal4_1 = new javax.swing.JLabel();
        lbLocal4_2 = new javax.swing.JLabel();
        lbLocal4_3 = new javax.swing.JLabel();
        lbLocal4_4 = new javax.swing.JLabel();
        lbLocal4_5 = new javax.swing.JLabel();
        lbLocal4_6 = new javax.swing.JLabel();
        lbLocal4_7 = new javax.swing.JLabel();
        lbLocal4_8 = new javax.swing.JLabel();
        lbLocal4_9 = new javax.swing.JLabel();
        lbLocal5_5 = new javax.swing.JLabel();
        lbLocal5_1 = new javax.swing.JLabel();
        lbLocal5_2 = new javax.swing.JLabel();
        lbLocal5_3 = new javax.swing.JLabel();
        lbLocal5_4 = new javax.swing.JLabel();
        lbLocal5_6 = new javax.swing.JLabel();
        lbLocal5_7 = new javax.swing.JLabel();
        lbLocal5_8 = new javax.swing.JLabel();
        lbLocal1_1 = new javax.swing.JLabel();
        lbLocal5_9 = new javax.swing.JLabel();
        lbLocal1_2 = new javax.swing.JLabel();
        lbLocal6_1 = new javax.swing.JLabel();
        lbLocal1_3 = new javax.swing.JLabel();
        lbLocal6_2 = new javax.swing.JLabel();
        lbLocal1_4 = new javax.swing.JLabel();
        lbLocal6_3 = new javax.swing.JLabel();
        lbLocal1_5 = new javax.swing.JLabel();
        lbLocal1_6 = new javax.swing.JLabel();
        lbLocal1_7 = new javax.swing.JLabel();
        lbLocal1_8 = new javax.swing.JLabel();
        lbLocal6_4 = new javax.swing.JLabel();
        lbLocal6_5 = new javax.swing.JLabel();
        lbLocal6_6 = new javax.swing.JLabel();
        lbLocal6_7 = new javax.swing.JLabel();
        lbLocal1_9 = new javax.swing.JLabel();
        lbLocal6_8 = new javax.swing.JLabel();
        lbLocal2_9 = new javax.swing.JLabel();
        lbLocal6_9 = new javax.swing.JLabel();
        lbLocal2_8 = new javax.swing.JLabel();
        lbLocal2_7 = new javax.swing.JLabel();
        lbLocal2_6 = new javax.swing.JLabel();
        lbLocal2_4 = new javax.swing.JLabel();
        lbLocal2_5 = new javax.swing.JLabel();
        lbLocal2_3 = new javax.swing.JLabel();
        lbLocal2_2 = new javax.swing.JLabel();
        lbLocal2_1 = new javax.swing.JLabel();
        lbLocal3_1 = new javax.swing.JLabel();
        lbLocal3_2 = new javax.swing.JLabel();
        lbLocal3_3 = new javax.swing.JLabel();
        lbLocal3_4 = new javax.swing.JLabel();
        lblSaidaNA = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblPorta = new javax.swing.JLabel();
        lblTimmerTon = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IDE LADDER - Editor de Comandos");

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        btnArquivo.setBackground(new java.awt.Color(255, 255, 255));
        btnArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/abrir.png"))); // NOI18N
        btnArquivo.setFocusable(false);
        btnArquivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnArquivo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArquivoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnArquivo);

        btnSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salvar.png"))); // NOI18N
        btnSalvar.setFocusable(false);
        btnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalvar);

        salvarComo.setBackground(new java.awt.Color(255, 255, 255));
        salvarComo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salvar como.png"))); // NOI18N
        salvarComo.setFocusable(false);
        salvarComo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        salvarComo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salvarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarComoActionPerformed(evt);
            }
        });
        jToolBar1.add(salvarComo);

        btnConfiguraPorta.setBackground(new java.awt.Color(255, 255, 255));
        btnConfiguraPorta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/configurarPorta.png"))); // NOI18N
        btnConfiguraPorta.setFocusable(false);
        btnConfiguraPorta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConfiguraPorta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConfiguraPorta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguraPortaActionPerformed(evt);
            }
        });
        jToolBar1.add(btnConfiguraPorta);

        btnVerificaConexao.setBackground(new java.awt.Color(255, 255, 255));
        btnVerificaConexao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/verificaConexao.png"))); // NOI18N
        btnVerificaConexao.setFocusable(false);
        btnVerificaConexao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVerificaConexao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVerificaConexao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificaConexaoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVerificaConexao);

        btnConfiguracao.setBackground(new java.awt.Color(255, 255, 255));
        btnConfiguracao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/configuração.png"))); // NOI18N
        btnConfiguracao.setFocusable(false);
        btnConfiguracao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConfiguracao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConfiguracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracaoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnConfiguracao);

        btnCarregar.setBackground(new java.awt.Color(255, 255, 255));
        btnCarregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/carregar.png"))); // NOI18N
        btnCarregar.setFocusable(false);
        btnCarregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCarregar.setName("Carregar Programação"); // NOI18N
        btnCarregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCarregar);
        btnCarregar.getAccessibleContext().setAccessibleName("Carregar Programação");
        btnCarregar.getAccessibleContext().setAccessibleDescription("Carregar Programação");

        lblContatoNA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/contatoNA.png"))); // NOI18N
        lblContatoNA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContatoNAMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblContatoNAMousePressed(evt);
            }
        });

        jLabel1.setText("Paleta de Blocos: ");

        lblContatoP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/contatoP.png"))); // NOI18N
        lblContatoP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContatoPMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblContatoPMousePressed(evt);
            }
        });

        lblContatoNF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/contatoNF.png"))); // NOI18N
        lblContatoNF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContatoNFMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblContatoNFMousePressed(evt);
            }
        });

        lblContatoN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/contatoN.png"))); // NOI18N
        lblContatoN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblContatoNMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblContatoNMousePressed(evt);
            }
        });

        lblSaidaNF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/saidaNF.png"))); // NOI18N
        lblSaidaNF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSaidaNFMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSaidaNFMousePressed(evt);
            }
        });

        lblSaidaP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/saidaP.png"))); // NOI18N
        lblSaidaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSaidaPMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSaidaPMousePressed(evt);
            }
        });

        lblSaidaN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/saidaN.png"))); // NOI18N
        lblSaidaN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSaidaNMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSaidaNMousePressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Saída em tempo real"));

        ptxtSaida.setEditable(false);
        jScrollPane2.setViewportView(ptxtSaida);

        jButton1.setText("Atualizar Comandos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnLimparSaida.setText("Limpar Saída");
        btnLimparSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparSaidaActionPerformed(evt);
            }
        });

        cbxAtivarSaida.setSelected(true);
        cbxAtivarSaida.setText("Ativar painel de Saída");
        cbxAtivarSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxAtivarSaidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxAtivarSaida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimparSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(cbxAtivarSaida))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimparSaida)
                            .addComponent(jButton1))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Comandos Ladder"));
        jPanel2.setToolTipText("");

        lbLocal3_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal3_5.setText("3");
        lbLocal3_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal3_5MouseClicked(evt);
            }
        });

        lbLocal3_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal3_6.setText("3");
        lbLocal3_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal3_6MouseClicked(evt);
            }
        });

        lbLocal3_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal3_7.setText("3");
        lbLocal3_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal3_7MouseClicked(evt);
            }
        });

        lbLocal3_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal3_8.setText("3");
        lbLocal3_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal3_8MouseClicked(evt);
            }
        });

        lbLocal3_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal3_9.setText("3");
        lbLocal3_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal3_9MouseClicked(evt);
            }
        });

        lbLocal4_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal4_1.setText("4");
        lbLocal4_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal4_1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbLocal4_1MousePressed(evt);
            }
        });

        lbLocal4_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal4_2.setText("4");
        lbLocal4_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal4_2MouseClicked(evt);
            }
        });

        lbLocal4_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal4_3.setText("4");
        lbLocal4_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal4_3MouseClicked(evt);
            }
        });

        lbLocal4_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal4_4.setText("4");
        lbLocal4_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal4_4MouseClicked(evt);
            }
        });

        lbLocal4_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal4_5.setText("4");
        lbLocal4_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal4_5MouseClicked(evt);
            }
        });

        lbLocal4_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal4_6.setText("4");
        lbLocal4_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal4_6MouseClicked(evt);
            }
        });

        lbLocal4_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal4_7.setText("4");
        lbLocal4_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal4_7MouseClicked(evt);
            }
        });

        lbLocal4_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal4_8.setText("4");

        lbLocal4_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal4_9.setText("4");

        lbLocal5_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal5_5.setText("5");

        lbLocal5_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal5_1.setText("5");
        lbLocal5_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal5_1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbLocal5_1MousePressed(evt);
            }
        });

        lbLocal5_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal5_2.setText("5");
        lbLocal5_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal5_2MouseClicked(evt);
            }
        });

        lbLocal5_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal5_3.setText("5");

        lbLocal5_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal5_4.setText("5");

        lbLocal5_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal5_6.setText("5");

        lbLocal5_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal5_7.setText("5");

        lbLocal5_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal5_8.setText("5");

        lbLocal1_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal1_1.setText("1");
        lbLocal1_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal1_1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbLocal1_1MousePressed(evt);
            }
        });

        lbLocal5_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal5_9.setText("5");

        lbLocal1_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal1_2.setText("1");
        lbLocal1_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal1_2MouseClicked(evt);
            }
        });

        lbLocal6_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal6_1.setText("6");
        lbLocal6_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal6_1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbLocal6_1MousePressed(evt);
            }
        });

        lbLocal1_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal1_3.setText("1");
        lbLocal1_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal1_3MouseClicked(evt);
            }
        });

        lbLocal6_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal6_2.setText("6");

        lbLocal1_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal1_4.setText("1");
        lbLocal1_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal1_4MouseClicked(evt);
            }
        });

        lbLocal6_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal6_3.setText("6");

        lbLocal1_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal1_5.setText("1");
        lbLocal1_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal1_5MouseClicked(evt);
            }
        });

        lbLocal1_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal1_6.setText("1");
        lbLocal1_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal1_6MouseClicked(evt);
            }
        });

        lbLocal1_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal1_7.setText("1");
        lbLocal1_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal1_7MouseClicked(evt);
            }
        });

        lbLocal1_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal1_8.setText("1");
        lbLocal1_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal1_8MouseClicked(evt);
            }
        });

        lbLocal6_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal6_4.setText("6");

        lbLocal6_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal6_5.setText("6");

        lbLocal6_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal6_6.setText("6");

        lbLocal6_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal6_7.setText("6");
        lbLocal6_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal6_7MouseClicked(evt);
            }
        });

        lbLocal1_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal1_9.setText("1");
        lbLocal1_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal1_9MouseClicked(evt);
            }
        });

        lbLocal6_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal6_8.setText("6");

        lbLocal2_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal2_9.setText("2");
        lbLocal2_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal2_9MouseClicked(evt);
            }
        });

        lbLocal6_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal6_9.setText("6");

        lbLocal2_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal2_8.setText("2");
        lbLocal2_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal2_8MouseClicked(evt);
            }
        });

        lbLocal2_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal2_7.setText("2");
        lbLocal2_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal2_7MouseClicked(evt);
            }
        });

        lbLocal2_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal2_6.setText("2");
        lbLocal2_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal2_6MouseClicked(evt);
            }
        });

        lbLocal2_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal2_4.setText("2");
        lbLocal2_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal2_4MouseClicked(evt);
            }
        });

        lbLocal2_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal2_5.setText("2");
        lbLocal2_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal2_5MouseClicked(evt);
            }
        });

        lbLocal2_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal2_3.setText("2");
        lbLocal2_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal2_3MouseClicked(evt);
            }
        });

        lbLocal2_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal2_2.setText("2");
        lbLocal2_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal2_2MouseClicked(evt);
            }
        });

        lbLocal2_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal2_1.setText("2");
        lbLocal2_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal2_1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbLocal2_1MousePressed(evt);
            }
        });

        lbLocal3_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal3_1.setText("3");
        lbLocal3_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal3_1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbLocal3_1MousePressed(evt);
            }
        });

        lbLocal3_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal3_2.setText("3");
        lbLocal3_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal3_2MouseClicked(evt);
            }
        });

        lbLocal3_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal3_3.setText("3");
        lbLocal3_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal3_3MouseClicked(evt);
            }
        });

        lbLocal3_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/condicao.png"))); // NOI18N
        lbLocal3_4.setText("3");
        lbLocal3_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLocal3_4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbLocal1_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLocal1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbLocal1_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLocal1_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLocal1_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLocal1_6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLocal1_7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLocal1_8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbLocal1_9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbLocal2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLocal2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbLocal2_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLocal2_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLocal2_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLocal2_6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLocal2_7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLocal2_8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbLocal2_9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbLocal4_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLocal4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lbLocal4_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLocal4_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLocal4_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLocal4_6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLocal4_7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLocal4_8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbLocal4_9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(lbLocal6_1)
                            .addGap(91, 91, 91)
                            .addComponent(lbLocal6_3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbLocal6_4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbLocal6_5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbLocal6_6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbLocal6_7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbLocal6_8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbLocal6_9))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbLocal5_1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbLocal5_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(78, 78, 78)
                                    .addComponent(lbLocal6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbLocal5_3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbLocal5_4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbLocal5_5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbLocal5_6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbLocal5_7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbLocal5_8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbLocal5_9)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lbLocal3_1)
                        .addGap(10, 10, 10)
                        .addComponent(lbLocal3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbLocal3_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLocal3_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLocal3_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLocal3_6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLocal3_7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbLocal3_8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbLocal3_9)))
                .addGap(54, 54, 54))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLocal1_2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocal1_1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocal1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocal1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocal1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocal1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocal1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocal1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocal1_9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLocal2_7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocal2_6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocal2_5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocal2_4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocal2_3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocal2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocal2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocal2_8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocal2_9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbLocal3_8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbLocal3_7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbLocal3_6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbLocal3_9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbLocal3_5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbLocal3_4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbLocal3_1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbLocal3_2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbLocal3_3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbLocal4_8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbLocal4_9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbLocal4_7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocal4_6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocal4_5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocal4_4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbLocal4_3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbLocal4_2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbLocal4_1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbLocal5_3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbLocal5_2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbLocal5_1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbLocal5_5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbLocal5_6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbLocal5_4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbLocal5_7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbLocal5_8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbLocal5_9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbLocal6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocal6_2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocal6_3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLocal6_4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbLocal6_6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbLocal6_5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbLocal6_7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbLocal6_8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbLocal6_9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        lbLocal3_5.getAccessibleContext().setAccessibleParent(this);
        lbLocal3_6.getAccessibleContext().setAccessibleParent(this);
        lbLocal3_7.getAccessibleContext().setAccessibleParent(this);
        lbLocal3_8.getAccessibleContext().setAccessibleParent(this);
        lbLocal3_9.getAccessibleContext().setAccessibleParent(this);
        lbLocal4_1.getAccessibleContext().setAccessibleParent(this);
        lbLocal4_2.getAccessibleContext().setAccessibleParent(this);
        lbLocal4_3.getAccessibleContext().setAccessibleParent(this);
        lbLocal4_4.getAccessibleContext().setAccessibleParent(this);
        lbLocal4_5.getAccessibleContext().setAccessibleParent(this);
        lbLocal4_6.getAccessibleContext().setAccessibleParent(this);
        lbLocal4_7.getAccessibleContext().setAccessibleParent(this);
        lbLocal4_8.getAccessibleContext().setAccessibleParent(this);
        lbLocal4_9.getAccessibleContext().setAccessibleParent(this);
        lbLocal5_5.getAccessibleContext().setAccessibleParent(this);
        lbLocal5_1.getAccessibleContext().setAccessibleParent(this);
        lbLocal5_2.getAccessibleContext().setAccessibleParent(this);
        lbLocal5_3.getAccessibleContext().setAccessibleParent(this);
        lbLocal5_4.getAccessibleContext().setAccessibleParent(this);
        lbLocal5_6.getAccessibleContext().setAccessibleParent(this);
        lbLocal5_7.getAccessibleContext().setAccessibleParent(this);
        lbLocal5_8.getAccessibleContext().setAccessibleParent(this);
        lbLocal1_1.getAccessibleContext().setAccessibleParent(this);
        lbLocal5_9.getAccessibleContext().setAccessibleParent(this);
        lbLocal1_2.getAccessibleContext().setAccessibleParent(this);
        lbLocal6_1.getAccessibleContext().setAccessibleParent(this);
        lbLocal1_3.getAccessibleContext().setAccessibleParent(this);
        lbLocal6_2.getAccessibleContext().setAccessibleParent(this);
        lbLocal1_4.getAccessibleContext().setAccessibleParent(this);
        lbLocal6_3.getAccessibleContext().setAccessibleParent(this);
        lbLocal1_5.getAccessibleContext().setAccessibleParent(this);
        lbLocal1_6.getAccessibleContext().setAccessibleParent(this);
        lbLocal1_7.getAccessibleContext().setAccessibleParent(this);
        lbLocal1_8.getAccessibleContext().setAccessibleParent(this);
        lbLocal6_4.getAccessibleContext().setAccessibleParent(this);
        lbLocal6_5.getAccessibleContext().setAccessibleParent(this);
        lbLocal6_6.getAccessibleContext().setAccessibleParent(this);
        lbLocal6_7.getAccessibleContext().setAccessibleParent(this);
        lbLocal1_9.getAccessibleContext().setAccessibleParent(this);
        lbLocal6_8.getAccessibleContext().setAccessibleParent(this);
        lbLocal2_9.getAccessibleContext().setAccessibleParent(this);
        lbLocal6_9.getAccessibleContext().setAccessibleParent(this);
        lbLocal2_8.getAccessibleContext().setAccessibleParent(this);
        lbLocal2_7.getAccessibleContext().setAccessibleParent(this);
        lbLocal2_6.getAccessibleContext().setAccessibleParent(this);
        lbLocal2_4.getAccessibleContext().setAccessibleParent(this);
        lbLocal2_5.getAccessibleContext().setAccessibleParent(this);
        lbLocal2_3.getAccessibleContext().setAccessibleParent(this);
        lbLocal2_2.getAccessibleContext().setAccessibleParent(this);
        lbLocal2_1.getAccessibleContext().setAccessibleParent(this);
        lbLocal3_1.getAccessibleContext().setAccessibleParent(this);
        lbLocal3_2.getAccessibleContext().setAccessibleParent(this);
        lbLocal3_3.getAccessibleContext().setAccessibleParent(this);
        lbLocal3_4.getAccessibleContext().setAccessibleParent(this);

        lblSaidaNA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/saidaNA.png"))); // NOI18N
        lblSaidaNA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSaidaNAMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSaidaNAMousePressed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações"));

        jLabel2.setText("Porta Configurada:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblPorta, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTimmerTon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/timmerTON.png"))); // NOI18N
        lblTimmerTon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTimmerTonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTimmerTonMousePressed(evt);
            }
        });

        jMenu1.setText("Arquivos");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ferramentas");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Configurações");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTimmerTon)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblContatoNA)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblContatoNF)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblContatoP)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblContatoN))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblSaidaNA)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblSaidaNF)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblSaidaP)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblSaidaN))
                                .addComponent(jSeparator1)))
                        .addContainerGap(75, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSaidaN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblContatoNA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblContatoNF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblContatoP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblContatoN, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSaidaNF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSaidaP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSaidaNA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(lblTimmerTon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblContatoNAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContatoNAMouseClicked

    }//GEN-LAST:event_lblContatoNAMouseClicked

    private void lblContatoNAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContatoNAMousePressed

    }//GEN-LAST:event_lblContatoNAMousePressed

    private void btnConfiguraPortaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguraPortaActionPerformed
        frmSelecionaPortas p = new frmSelecionaPortas();
        p.setVisible(true);
        //
    }//GEN-LAST:event_btnConfiguraPortaActionPerformed

    private void lblContatoPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContatoPMouseClicked

    }//GEN-LAST:event_lblContatoPMouseClicked

    private void lblContatoPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContatoPMousePressed

    }//GEN-LAST:event_lblContatoPMousePressed

    private void lblContatoNFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContatoNFMouseClicked

    }//GEN-LAST:event_lblContatoNFMouseClicked

    private void lblContatoNFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContatoNFMousePressed

    }//GEN-LAST:event_lblContatoNFMousePressed

    private void lblSaidaNAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaidaNAMouseClicked

    }//GEN-LAST:event_lblSaidaNAMouseClicked

    private void lblSaidaNAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaidaNAMousePressed

    }//GEN-LAST:event_lblSaidaNAMousePressed

    private void lblContatoNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContatoNMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblContatoNMouseClicked

    private void lblContatoNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblContatoNMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblContatoNMousePressed

    private void btnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarActionPerformed
        ControleComunicacao envia = new ControleComunicacao();

        try {
            int c = envia.enviaProg(qntdLinhas, qntdColunas, labelContatos, lineMatriz);
            switch (c) {
                case 1:
                    JOptionPane.showMessageDialog(null, "Enviado Corretamente!");
                    break;
                case 0:
                    JOptionPane.showMessageDialog(null, "Erro ao Enviar!", "Envio", JOptionPane.WARNING_MESSAGE);
                    break;
                default:
                    break;
            }

        } catch (IOException ex) {
            Logger.getLogger(FrmEditorComandos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(FrmEditorComandos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JSONException ex) {
            Logger.getLogger(FrmEditorComandos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(FrmEditorComandos.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnCarregarActionPerformed

    private void lblSaidaNFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaidaNFMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSaidaNFMouseClicked

    private void lblSaidaNFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaidaNFMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSaidaNFMousePressed

    private void lblSaidaPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaidaPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSaidaPMouseClicked

    private void lblSaidaPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaidaPMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSaidaPMousePressed

    private void lblSaidaNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaidaNMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSaidaNMouseClicked

    private void lblSaidaNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaidaNMousePressed
        
    }//GEN-LAST:event_lblSaidaNMousePressed

    private void lbLocal6_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal6_1MousePressed

    }//GEN-LAST:event_lbLocal6_1MousePressed

    private void lbLocal6_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal6_1MouseClicked
      clickLabel(evt);    
    }//GEN-LAST:event_lbLocal6_1MouseClicked

    private void lbLocal5_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal5_1MousePressed
      
    }//GEN-LAST:event_lbLocal5_1MousePressed

    private void lbLocal5_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal5_1MouseClicked
       clickLabel(evt);    
    }//GEN-LAST:event_lbLocal5_1MouseClicked

    private void lbLocal4_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal4_1MousePressed
         
    }//GEN-LAST:event_lbLocal4_1MousePressed

    private void lbLocal4_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal4_1MouseClicked
       clickLabel(evt);    
    }//GEN-LAST:event_lbLocal4_1MouseClicked

    private void lbLocal3_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal3_1MousePressed
        
    }//GEN-LAST:event_lbLocal3_1MousePressed

    private void lbLocal3_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal3_1MouseClicked
       clickLabel(evt);    
    }//GEN-LAST:event_lbLocal3_1MouseClicked

    private void lbLocal2_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal2_1MousePressed

    }//GEN-LAST:event_lbLocal2_1MousePressed

    private void lbLocal2_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal2_1MouseClicked
       clickLabel(evt);     
    }//GEN-LAST:event_lbLocal2_1MouseClicked

    private void lbLocal1_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal1_1MousePressed

    }//GEN-LAST:event_lbLocal1_1MousePressed

    private void lbLocal1_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal1_1MouseClicked
        clickLabel(evt);        
    }//GEN-LAST:event_lbLocal1_1MouseClicked

    private void lbLocal6_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal6_7MouseClicked
       clickLabel(evt);    
    }//GEN-LAST:event_lbLocal6_7MouseClicked

    private void lbLocal1_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal1_2MouseClicked
        clickLabel(evt);    
    }//GEN-LAST:event_lbLocal1_2MouseClicked

    private void lbLocal1_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal1_3MouseClicked
        clickLabel(evt);    
    }//GEN-LAST:event_lbLocal1_3MouseClicked

    private void lbLocal1_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal1_4MouseClicked
        clickLabel(evt);    
    }//GEN-LAST:event_lbLocal1_4MouseClicked

    private void lbLocal1_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal1_5MouseClicked
        clickLabel(evt);    
    }//GEN-LAST:event_lbLocal1_5MouseClicked

    private void lbLocal1_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal1_6MouseClicked
       clickLabel(evt);    
    }//GEN-LAST:event_lbLocal1_6MouseClicked

    private void lbLocal1_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal1_7MouseClicked
        clickLabel(evt);    
    }//GEN-LAST:event_lbLocal1_7MouseClicked

    private void lbLocal1_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal1_8MouseClicked
       clickLabel(evt);    
    }//GEN-LAST:event_lbLocal1_8MouseClicked

    private void lbLocal1_9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal1_9MouseClicked
        clickLabel(evt);    
    }//GEN-LAST:event_lbLocal1_9MouseClicked

    private void lbLocal2_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal2_2MouseClicked
       clickLabel(evt);    
    }//GEN-LAST:event_lbLocal2_2MouseClicked

    private void lbLocal2_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal2_3MouseClicked
        clickLabel(evt);    
    }//GEN-LAST:event_lbLocal2_3MouseClicked

    private void lbLocal2_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal2_4MouseClicked
       clickLabel(evt);    
    }//GEN-LAST:event_lbLocal2_4MouseClicked

    private void lbLocal2_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal2_5MouseClicked
        clickLabel(evt);    
    }//GEN-LAST:event_lbLocal2_5MouseClicked

    private void lbLocal2_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal2_6MouseClicked
        clickLabel(evt);    
    }//GEN-LAST:event_lbLocal2_6MouseClicked

    private void lbLocal2_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal2_7MouseClicked
        clickLabel(evt);    
    }//GEN-LAST:event_lbLocal2_7MouseClicked

    private void lbLocal2_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal2_8MouseClicked
        clickLabel(evt);    
    }//GEN-LAST:event_lbLocal2_8MouseClicked

    private void lbLocal2_9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal2_9MouseClicked
       clickLabel(evt);    
    }//GEN-LAST:event_lbLocal2_9MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ControleProgramacao cProg = new ControleProgramacao();
        try {
            ptxtSaida.setText(ptxtSaida.getText() + "--------------------------------------------- ATUALIZANDO --------------------------------------------- \n");
            ptxtSaida.setText(ptxtSaida.getText() + cProg.organizaComandosExibicao(qntdLinhas, qntdColunas, labelContatos, lineMatriz));

        } catch (IOException | ParseException | JSONException ex) {
            Logger.getLogger(FrmEditorComandos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clickLabel(java.awt.event.MouseEvent evt) {
        JLabel labelAux = (JLabel)evt.getComponent();
        if ((evt.getModifiers() & MouseEvent.BUTTON3_MASK) != 0) {
            FrmOpComandos formAlteraComando = new FrmOpComandos(new javax.swing.JFrame(), true, (JLabel)evt.getComponent(), listaComandos);
            formAlteraComando.setVisible(true);
            labelAux = formAlteraComando.getLabel();
            listaComandos = formAlteraComando.getLista();
        } else {
            labelAux.setText("" + (labelAux.getText().equals("6") ? "1" : Integer.parseInt(labelAux.getText()) + 1));
        }
    }
    
    private void btnLimparSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparSaidaActionPerformed
        ptxtSaida.setText("");
    }//GEN-LAST:event_btnLimparSaidaActionPerformed

    private void cbxAtivarSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxAtivarSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxAtivarSaidaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        salva(false);
    }//GEN-LAST:event_btnSalvarActionPerformed
// IMPORTANTE - REFORMULAR, COLOCAR NO CONTROLEARQUIVO
    public void salva(boolean novoDiretorio) {

        JSONObject progSalva = new JSONObject();
        try {
            progSalva = geraJsonSalvar();
        } catch (JSONException ex) {
            Logger.getLogger(FrmEditorComandos.class.getName()).log(Level.SEVERE, null, ex);
        }
        ControleArquivo cArquivo = new ControleArquivo();
        boolean verificaDiretorio = false;

        if (diretorioProjeto == null || novoDiretorio) {
            verificaDiretorio = pegaDiretorio();
        } else {
            verificaDiretorio = true;
        }
        if (verificaDiretorio) {
            try {
                cArquivo.salvaProg(progSalva, diretorioProjeto, nomeProjeto);
            } catch (IOException | JSONException | ParseException ex) {
                Logger.getLogger(FrmEditorComandos.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(null, "Salvo com sucesso!");

        } else {
            JOptionPane.showMessageDialog(null, "Diretório não selecionado!");
        }
    }
// IMPORTANTE - REFORMULAR, COLOCAR NO CONTROLEARQUIVO
    public boolean pegaDiretorio() {
        boolean verifica = false;

        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int res = fc.showOpenDialog(null);

        if (res == JFileChooser.APPROVE_OPTION) {
            verifica = true;
            File diretorio = new File(fc.getSelectedFile().getAbsolutePath());
            diretorioProjeto = diretorio;
        }
        return verifica;

    }
    private void btnArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArquivoActionPerformed
        if(JOptionPane.showConfirmDialog( null,"Deseja Salvar o Projeto Atual?", "Salvar",JOptionPane.YES_NO_OPTION) == 0){
            salva(false);
        }
           JFileChooser arquivo = new JFileChooser();
        JSONParser parser = new JSONParser();
        FileNameExtensionFilter filtroPDF = new FileNameExtensionFilter("Arquivos JSON", "json");
        JSONObject leitura = new JSONObject();
       
        arquivo.addChoosableFileFilter(filtroPDF);
        arquivo.setAcceptAllFileFilterUsed(false);
        
        if (arquivo.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            FrmEditorComandos a = new FrmEditorComandos();
             a.setVisible(true);
           
            
            try {
                leitura = (JSONObject) parser.parse(new FileReader(arquivo.getSelectedFile().getAbsolutePath()));
               } catch (ParseException | IOException ex) {
                Logger.getLogger(frmInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try {
                File diretorio = new File(arquivo.getSelectedFile().getAbsolutePath());
                a.abrirProjeto("alterar", diretorio , leitura);
            } catch (JSONException ex) {
                Logger.getLogger(frmInicial.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            this.dispose();
        }
    }//GEN-LAST:event_btnArquivoActionPerformed

    private void salvarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarComoActionPerformed
        salva(true);
    }//GEN-LAST:event_salvarComoActionPerformed

    private void lblTimmerTonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTimmerTonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTimmerTonMouseClicked

    private void lblTimmerTonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTimmerTonMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTimmerTonMousePressed

    private void lbLocal3_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal3_2MouseClicked
        clickLabel(evt);    
    }//GEN-LAST:event_lbLocal3_2MouseClicked

    private void lbLocal3_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal3_3MouseClicked
        clickLabel(evt);    
    }//GEN-LAST:event_lbLocal3_3MouseClicked

    private void lbLocal3_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal3_4MouseClicked
        clickLabel(evt);    
    }//GEN-LAST:event_lbLocal3_4MouseClicked

    private void lbLocal3_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal3_5MouseClicked
        clickLabel(evt);    
    }//GEN-LAST:event_lbLocal3_5MouseClicked

    private void lbLocal3_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal3_6MouseClicked
       clickLabel(evt);    
    }//GEN-LAST:event_lbLocal3_6MouseClicked

    private void lbLocal3_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal3_7MouseClicked
        clickLabel(evt);    
    }//GEN-LAST:event_lbLocal3_7MouseClicked

    private void lbLocal3_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal3_8MouseClicked
        clickLabel(evt);    
    }//GEN-LAST:event_lbLocal3_8MouseClicked

    private void lbLocal3_9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal3_9MouseClicked
        clickLabel(evt);    
    }//GEN-LAST:event_lbLocal3_9MouseClicked

    private void lbLocal4_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal4_2MouseClicked
       clickLabel(evt);    
    }//GEN-LAST:event_lbLocal4_2MouseClicked

    private void lbLocal4_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal4_3MouseClicked
        clickLabel(evt);    
    }//GEN-LAST:event_lbLocal4_3MouseClicked

    private void lbLocal4_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal4_4MouseClicked
        clickLabel(evt);    
    }//GEN-LAST:event_lbLocal4_4MouseClicked

    private void lbLocal4_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal4_5MouseClicked
        clickLabel(evt);    
    }//GEN-LAST:event_lbLocal4_5MouseClicked

    private void lbLocal4_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal4_6MouseClicked
       clickLabel(evt);    
    }//GEN-LAST:event_lbLocal4_6MouseClicked

    private void lbLocal4_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal4_7MouseClicked
        clickLabel(evt);
    }//GEN-LAST:event_lbLocal4_7MouseClicked

    private void lbLocal5_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLocal5_2MouseClicked
        clickLabel(evt);    
    }//GEN-LAST:event_lbLocal5_2MouseClicked

    private void btnConfiguracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracaoActionPerformed
        JOptionPane.showMessageDialog(null, "Ops... Recurso ainda não implementado! Aguarde novas atualizações.");
    }//GEN-LAST:event_btnConfiguracaoActionPerformed

    private void btnVerificaConexaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificaConexaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerificaConexaoActionPerformed

    private int alteraPorta(int atual) {
        int porta;
        if (atual < 6) {
            porta = atual + 1;
        } else {
            porta = 1;
        }
        return porta;
    }

    private void populaVariaveis() {

        JLabel[] labelLineAux = {lbLocal1_1, lbLocal1_2, lbLocal1_3, lbLocal1_4, lbLocal1_5, lbLocal1_6, lbLocal1_7, lbLocal1_8, lbLocal1_9,
            lbLocal2_1, lbLocal2_2, lbLocal2_3, lbLocal2_4, lbLocal2_5, lbLocal2_6, lbLocal2_7, lbLocal2_8, lbLocal2_9,
            lbLocal3_1, lbLocal3_2, lbLocal3_3, lbLocal3_4, lbLocal3_5, lbLocal3_6, lbLocal3_7, lbLocal3_8, lbLocal3_9,
            lbLocal4_1, lbLocal4_2, lbLocal4_3, lbLocal4_4, lbLocal4_5, lbLocal4_6, lbLocal4_7, lbLocal4_8, lbLocal4_9,
            lbLocal5_1, lbLocal5_2, lbLocal5_3, lbLocal5_4, lbLocal5_5, lbLocal5_6, lbLocal5_7, lbLocal5_8, lbLocal5_9,
            lbLocal6_1, lbLocal6_2, lbLocal6_3, lbLocal6_4, lbLocal6_5, lbLocal6_6, lbLocal6_7, lbLocal6_8, lbLocal6_9,};

        labelLine = labelLineAux;

        JLabel[] labelContatosAux = {lblContatoNA, lblContatoNF, lblContatoP, lblContatoN, lblSaidaNA, lblSaidaNF, lblSaidaP, lblSaidaN, lblTimmerTon
        };
        labelContatos = labelContatosAux;

        int cont = 0;

        for (int i = 0; i < qntdLinhas; i++) {
            for (int c = 0; c < qntdColunas; c++) {
                lineMatriz[i][c] = labelLine[cont];
                cont++;
            }
        }
    }

    private void movimentacoesBlocosEntrada() {
        MouseListener ml = new MouseListener() {

            @Override
            public void mouseClicked(MouseEvent e) {

            }

            @Override
            public void mousePressed(MouseEvent e) {

                JComponent jc = (JComponent) e.getSource();
                TransferHandler th = jc.getTransferHandler();
                th.exportAsDrag(jc, e, TransferHandler.COPY);

                if (cbxAtivarSaida.isSelected()) {
                    ControleProgramacao cProg = new ControleProgramacao();
                    try {
                        ptxtSaida.setText(ptxtSaida.getText() + "--------------------------------------------- ATUALIZANDO --------------------------------------------- \n");
                        ptxtSaida.setText(ptxtSaida.getText() + cProg.organizaComandosExibicao(qntdLinhas, qntdColunas, labelContatos, lineMatriz));
                    } catch (IOException | ParseException | JSONException ex) {
                        Logger.getLogger(FrmEditorComandos.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        };

        for (JLabel aux : labelContatos) {
            aux.setBounds(aux.getX(), aux.getY(), aux.getWidth(), aux.getHeight());
            aux.addMouseListener(ml);
            aux.setTransferHandler(new TransferHandler("icon"));

            add(aux);
        }

        for (JLabel aux : labelLine) {

            aux.setTransferHandler(new TransferHandler("icon"));
        }

    }

    public JSONObject geraJsonSalvar() throws JSONException {
        JSONObject salvaProg = new JSONObject();
        JSONObject auxComandos = new JSONObject();
        JSONObject auxPortas = new JSONObject();

        for (int i = 0; i < labelLine.length; i++) {
            File arquivo;
            arquivo = new File(labelLine[i].getIcon().toString());
            auxComandos.put("comando" + i, arquivo.getName());
            auxPortas.put("porta" + i, labelLine[i].getText());
        }

        salvaProg.put("comandos", auxComandos);
        salvaProg.put("portas", auxPortas);

        return salvaProg;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditorComandos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditorComandos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditorComandos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditorComandos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEditorComandos().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArquivo;
    private javax.swing.JButton btnCarregar;
    private javax.swing.JButton btnConfiguraPorta;
    private javax.swing.JButton btnConfiguracao;
    private javax.swing.JButton btnLimparSaida;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVerificaConexao;
    private javax.swing.JCheckBox cbxAtivarSaida;
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbLocal1_1;
    private javax.swing.JLabel lbLocal1_2;
    private javax.swing.JLabel lbLocal1_3;
    private javax.swing.JLabel lbLocal1_4;
    private javax.swing.JLabel lbLocal1_5;
    private javax.swing.JLabel lbLocal1_6;
    private javax.swing.JLabel lbLocal1_7;
    private javax.swing.JLabel lbLocal1_8;
    private javax.swing.JLabel lbLocal1_9;
    private javax.swing.JLabel lbLocal2_1;
    private javax.swing.JLabel lbLocal2_2;
    private javax.swing.JLabel lbLocal2_3;
    private javax.swing.JLabel lbLocal2_4;
    private javax.swing.JLabel lbLocal2_5;
    private javax.swing.JLabel lbLocal2_6;
    private javax.swing.JLabel lbLocal2_7;
    private javax.swing.JLabel lbLocal2_8;
    private javax.swing.JLabel lbLocal2_9;
    private javax.swing.JLabel lbLocal3_1;
    private javax.swing.JLabel lbLocal3_2;
    private javax.swing.JLabel lbLocal3_3;
    private javax.swing.JLabel lbLocal3_4;
    private javax.swing.JLabel lbLocal3_5;
    private javax.swing.JLabel lbLocal3_6;
    private javax.swing.JLabel lbLocal3_7;
    private javax.swing.JLabel lbLocal3_8;
    private javax.swing.JLabel lbLocal3_9;
    private javax.swing.JLabel lbLocal4_1;
    private javax.swing.JLabel lbLocal4_2;
    private javax.swing.JLabel lbLocal4_3;
    private javax.swing.JLabel lbLocal4_4;
    private javax.swing.JLabel lbLocal4_5;
    private javax.swing.JLabel lbLocal4_6;
    private javax.swing.JLabel lbLocal4_7;
    private javax.swing.JLabel lbLocal4_8;
    private javax.swing.JLabel lbLocal4_9;
    private javax.swing.JLabel lbLocal5_1;
    private javax.swing.JLabel lbLocal5_2;
    private javax.swing.JLabel lbLocal5_3;
    private javax.swing.JLabel lbLocal5_4;
    private javax.swing.JLabel lbLocal5_5;
    private javax.swing.JLabel lbLocal5_6;
    private javax.swing.JLabel lbLocal5_7;
    private javax.swing.JLabel lbLocal5_8;
    private javax.swing.JLabel lbLocal5_9;
    private javax.swing.JLabel lbLocal6_1;
    private javax.swing.JLabel lbLocal6_2;
    private javax.swing.JLabel lbLocal6_3;
    private javax.swing.JLabel lbLocal6_4;
    private javax.swing.JLabel lbLocal6_5;
    private javax.swing.JLabel lbLocal6_6;
    private javax.swing.JLabel lbLocal6_7;
    private javax.swing.JLabel lbLocal6_8;
    private javax.swing.JLabel lbLocal6_9;
    private javax.swing.JLabel lblContatoN;
    private javax.swing.JLabel lblContatoNA;
    private javax.swing.JLabel lblContatoNF;
    private javax.swing.JLabel lblContatoP;
    private javax.swing.JLabel lblPorta;
    private javax.swing.JLabel lblSaidaN;
    private javax.swing.JLabel lblSaidaNA;
    private javax.swing.JLabel lblSaidaNF;
    private javax.swing.JLabel lblSaidaP;
    private javax.swing.JLabel lblTimmerTon;
    private javax.swing.JTextPane ptxtSaida;
    private javax.swing.JButton salvarComo;
    // End of variables declaration//GEN-END:variables
}
